### ISSUE TITLE
Black font on black background

### ISSUE THREAD

**Issue by phi-whiterabbit** [tobexyz/yaacc-code#1]
Using version 2.0.0 as built by f-droid i have text rendered in black fonts on a black background, which makes the app unusable.

Interestingly, if i decend into some subfolder in the content tab and touch "back" (or whatever that "button" is called), then the text turns white for a moment.

**Comment by alazyworkaholic** [comment]
Exact same behavior for me. LG-H873, Android 8.0.0

**Comment by tobexyz** [comment]
Thank you for reporting this issue. I'll only tested using Android 6 at the moment. I'll take a look at Android 8

**Comment by tobexyz** [comment]
Fixed in 2.0.2
