### ISSUE TITLE
Change YAACC language by App languages system setting screen

### ISSUE THREAD

**Issue by Korb** [tobexyz/yaacc-code#112]
I suggest you consider changing the language of the application through a single control center for the languages of installed applications, available in the latest versions of Google Android. Read more about it in the article "[Change app language on your Android phone](https://support.google.com/android/answer/12395118)" of the official OS help. [Screenshot](https://drive.google.com/file/d/1rhT3cFpo8cpeLrXIPteFH-0202ks_IYy/view)

**Comment by ildar** [comment]
I see just one language besides English in this app: DE.
Do you want a German interface?

**Comment by Korb** [comment]
@ildar, I also only see two languages so far. And I really hope that over time there will be more of them. And they will be implemented in the application in the manner recommended by Google.

**Comment by tobexyz** [comment]
Which languages are you most interested in?

**Comment by tobexyz** [comment]
Has to be implemented like as described here https://developer.android.com/guide/topics/resources/app-languages?hl=en#groovy

**Comment by Korb** [comment]
> now it is possible to change the language for the app.

In version 4.2.1?

**Comment by tobexyz** [comment]
Yes, it will be part of the next upcoming release. Hopefully I can release it soon

**Comment by Korb** [comment]
![Image](https://github.com/user-attachments/assets/e72d2b01-cc08-4ef8-9d60-1dafab1823d4)

Thank you!
