### ISSUE TITLE
Restore scroll position when going back in content view

### ISSUE THREAD

**Issue by cweiske** [tobexyz/yaacc-code#115]
When using the back button inside the directory structure of the content view, the list is scrolled to the top.
My artist list is ~150 entries long, so scrolling down again takes some time.

Please restore the last scroll position when going back in the content tree.

Also, there is no scroll bar/indicator on the right side in this list.

<img src="https://private-user-images.githubusercontent.com/59036/325535541-0e090a9e-5e1f-4040-b902-9fabd35381b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzQ1ODUsIm5iZiI6MTcxNDAzNDI4NSwicGF0aCI6Ii81OTAzNi8zMjU1MzU1NDEtMGUwOTBhOWUtNWUxZi00MDQwLWI5MDItOWZhYmQzNTM4MWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA4MzgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNzc2OTNlNmMwODYyNTFiZTllYzNlYmU3OTUyYzU2YWI0ZTA1ZjE2Mzg4YzQ5NjgzZWNjZTJlMmI3ZTNiZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vnwY8QKSRkQAPeNmGRudw3pRm6afXOmirwMkmHgbzzo" alt="Screenshot_20240425-100346_YAACC" height="200px">

**Comment by tobexyz** [comment]
back navigation now scrolls to the last position

**Comment by cweiske** [comment]
I just compiled commit 53f4cac and tried it; it does not work.

I do:
1. Select sender
2. Select content "Audio" > "Artists" > scroll down to "Dido" and select it
3. Press the yaacc "<-" button
4. Artists list is again at the start position; it's not scrolled down to "Dido". Dido is not visible.

The same happens when I use the Android back button.

----

This happens on a Fairphone 4, Android 14 (LineageOS 21).

**Comment by tobexyz** [comment]
confirmed, thank you for testing the app
currently it only seems to work on back swiping and not on click on the back navigation. I'll fix it

**Comment by tobexyz** [comment]
hopefully it is now fixed. Didn't expected that scrolling a RecylerView is such tricky :smile:

**Comment by cweiske** [comment]
Restoring the scroll position does work now if it was on the first page of the results!

But when yaacc paged to the second or third page of the result set, restoring does not work:

1. Select sender
2. Select content "Audio" > "Artists" > scroll down to "Fool's garden". Scrolling will stop and YAACC will load the next page of artists
3. Scroll down to "Nirvana". Scrolling will stop and YAACC will load the 3rd page of artists
4. Scroll down to "Taylor Swift" and select it
5. Press the yaacc "<-" button
6. Artists list is again at the start position; it's not scrolled down to "Taylor Swift". "Taylor Swift" is not visible.

(This scrolling behaviour is a nuisance, but that's a different issue.)

**Comment by tobexyz** [comment]
The scrolling behaviour is crazy. I'll take another look at it. 

Btw. the batch size of the content search can be adjusted in the settings. The default size is 50 items. If you increase it, the scrolling would be more fluently

**Comment by tobexyz** [comment]
now it is also working on long lists

**Comment by tobexyz** [comment]
fixed wrong commit

**Comment by cweiske** [comment]
Going back works fine now - thanks.
