### ISSUE TITLE
Option to disable horizontal scrolling

### ISSUE THREAD

**Issue by cweiske** [tobexyz/yaacc-code#116]
When using YAACC on the landscape phone on my nightstand, I often accidentially trigger the horizontal scrolling that switches between sender/content/receiver/player - when all I wanted was to scroll the content list. This also happens on my normal vertical phone.

I'm fully fine with clicking the buttons in the top navigation bar to switch between the views and do not need the horizontal scrolling.
Please disable it completely or provide an option to disable it.

**Comment by tobexyz** [comment]
feature added the behavior is now configurable

**Comment by cweiske** [comment]
Thank you!
