### ISSUE TITLE
Player view: Song progress not updated after display was off

### ISSUE THREAD

**Issue by cweiske** [tobexyz/yaacc-code#117]
When starting to play a music track, the music player screen shows the length of the song and the current play position. The play position gets updated automatically.

Now I turn off the phone's display, turn it on again and unlock the screen. The current play position does not get updated anymore.

When the next song is played automatically, the play position updates again.

This is with YACC 4.1.0 from F-Droid on two phones: Fairphone 4 with LineageOS 20 (Android 13), and a Wileyfox Swift with LineageOS 17 (Android 10).

**Comment by ildar** [comment]
hi! I don't see such a behavior. But that's probably because I turned off
Battery optimization (power saving) for this app.

**Comment by cweiske** [comment]
I disabled battery optimization for YAACC on both devices and the problem still occurs.

**Comment by tobexyz** [comment]
fixed.

**Comment by cweiske** [comment]
:partying_face:

**Comment by cweiske** [comment]
I can confirm that it works now - thank you Tobe.
