### ISSUE TITLE
log is useless

### ISSUE THREAD

**Issue by ildar** [tobexyz/yaacc-code#122]
everytime I look into "Log" after my TV fails to show a video, Log is full of useless messages and no media renderer reports.

**Comment by tobexyz** [comment]
Did you changed the log level in settings?
https://tobexyz.github.io/yaacc-code/settings/

**Comment by ildar** [comment]
I'll try and let you know

**Comment by tobexyz** [comment]
changed the log level of all classes implementing the upnp stack from debug and info to verbose
