### ISSUE TITLE
YAACC hangs directly after start

### ISSUE THREAD

**Issue by cweiske** [tobexyz/yaacc-code#16]
I installed YAACC 2.1.1 freshly on a Nexus 7 with LineageOS (Android 7.1.2, Linage 14.1-20181227-flo).

When starting it, it shows the normal UI with the 4 tabs (sender, content, receiver, player).

When I started it the first time after installation, I could access the renderers tab and see my players. Then it would hang when trying to browse the Gerbera UPnP server, and since them it always hangs.

Android then asks me if I want to kill the app.

In the logs, I see dozens of "remoteDeviceUpdated" entries for my 4 renderers.

Log entries related to the hang:

> I InputDispatcher: Application is not responding: Window{8570bc5 u0 de.yaacc/de.yaacc.browser.TabBrowserActivity}.  It has been 5003.5ms since event, 5003.3ms since wait started.  Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 5.  Wait queue head age: 5706.5ms.
> I WindowManager: Input event dispatching timed out sending to de.yaacc/de.yaacc.browser.TabBrowserActivity.  Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 5.  Wait queue head age: 5706.5ms.

----

If I force-stop it in the settings and then delete all files and caches, and then start it again, it does not hang.

As soon as I select my Gerbera UPnP server in the "sender" tab and choose one of the folders in "content", it hangs - even after restarts.

----

Trace:
```
suspend all histogram:  Sum: 5.661ms 99% C.I. 1.146us-900.480us Avg: 131.651us Max: 915us
DALVIK THREADS (35):
"main" prio=5 tid=1 Runnable
  | group="main" sCount=0 dsCount=0 obj=0x74412250 self=0xb4285400
  | sysTid=3545 nice=-10 cgrp=default sched=0/0 handle=0xb6f82534
  | state=R schedstat=( 0 0 0 ) utm=1174 stm=18 core=1 HZ=100
  | stack=0xbe377000-0xbe379000 stackSize=8MB
  | held mutexes= "mutator lock"(shared held)
  at de.yaacc.upnp.UpnpClient.browseSync(UpnpClient.java:590)
  at de.yaacc.upnp.UpnpClient.browseSync(UpnpClient.java:563)
  at de.yaacc.browser.BrowseItemAdapter.initialize(BrowseItemAdapter.java:77)
  at de.yaacc.browser.BrowseItemAdapter.<init>(BrowseItemAdapter.java:69)
  at de.yaacc.browser.ContentListActivity$1.run(ContentListActivity.java:237)
  at android.app.Activity.runOnUiThread(Activity.java:5871)
  at de.yaacc.browser.ContentListActivity.populateItemList(ContentListActivity.java:230)
  at de.yaacc.browser.ContentListActivity.onResume(ContentListActivity.java:77)
  at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
  at android.app.Activity.performResume(Activity.java:6788)
  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3431)
  at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:147)
  at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:348)
  at android.widget.TabHost$IntentContentStrategy.getContentView(TabHost.java:724)
  at android.widget.TabHost.setCurrentTab(TabHost.java:388)
  at de.yaacc.browser.TabBrowserActivity$1.run(TabBrowserActivity.java:166)
  at android.app.Activity.runOnUiThread(Activity.java:5871)
  at de.yaacc.browser.TabBrowserActivity.setCurrentTab(TabBrowserActivity.java:161)
  at de.yaacc.browser.ServerListClickListener.onItemClick(ServerListClickListener.java:47)
  at android.widget.AdapterView.performItemClick(AdapterView.java:310)
  at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
  at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
  at android.widget.AbsListView$3.run(AbsListView.java:4054)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6186)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

Full trace file: [yaacc-hangs.traces.txt.gz](https://github.com/tobexyz/yaacc-code/files/2742698/yaacc-hangs.traces.txt.gz)

**Comment by tobexyz** [comment]
As in issue #9 yaacc doesn't fill the content list lazy at the moment. That's why the app hangs on loading large libraries. Another problem seams to be that the query is done synchronously on the ui threat. I have to focus this...

**Comment by tobexyz** [comment]
I've implemented a first solution in branch ```issue#9```. Items now loaded async. It would be helpful if anyone can additionally confirm that the implementation on the branch fixes the problem.

**Comment by cweiske** [comment]
No, it does not help.

The problem occurs with smaller directories already (~20 entries).
Log:
```
01-13 18:55:51.733   551   630 D WifiStateMachine: updateCapabilities for config:home.cweiske.defalse,false
01-13 18:55:54.494 30838 30838 D de.yaacc.browser.Navigator: pushNavigation: 368546
01-13 18:55:54.499   222   357 D ACDB-LOADER: ACDB -> send_afe_cal
01-13 18:55:54.502 30838 30838 D de.yaacc.browser.BrowseItemAdapter: loadMore from: 0
01-13 18:55:54.507 30838 30881 D de.yaacc.upnp.UpnpClient: #####Service found: urn:upnp-org:serviceId:ContentDirectory Type: urn:schemas-upnp-org:service:ContentDirectory:1
01-13 18:55:54.512   222   357 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback
01-13 18:55:54.612 30838 30871 D de.yaacc.upnp.callback.contentdirectory.ContentDirectoryBrowseActionCallback: RAW-Result: <DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/"><container id="369015" parentID="368546" restricted="1" childCount="4"><dc:title>Detlev Jöcker</dc:title><upnp:class>object.container</upnp:class></container><container id="368971" parentID="368546" restricted="1" childCount="1"><dc:title>Familie Sonntag</dc:title><upnp:class>object.container</upnp:class></container><container id="368652" parentID="368546" restricted="1" childCount="1"><dc:title>Kindercollection</dc:title><upnp:class>object.container</upnp:class></container><container id="368800" parentID="368546" restricted="1" childCount="1"><dc:title>Lieder aus dem Kindergarten</dc:title><upnp:class>object.container</upnp:class></container><container id="368894" parentID="368546" restricted="1" childCount="1"><dc:title>Reinhard Lakomy &amp; Monika Ehrhardt</dc:title><upnp:class>object.container</upnp:class></container><container id="368616" parentID="368546" restricted="1" childCount="1"><dc:title>Reinhard Mey</dc:title><upnp:class>object.container</upnp:class></container><container id="368547" parentID="368546" restricted="1" childCount="1"><dc:title>Rossmann</dc:title><upnp:class>object.container</upnp:class></container><container id="368840" parentID="368546" restricted="1" childCount="2"><dc:title>Sven Nordqvist</dc:title><upnp:class>object.container</upnp:class></container><container id="368938" parentID="368546" restricted="1" childCount="1"><dc:title>Traditionelle Kinderlieder</dc:title><upnp:class>object.container</upnp:class></container><container id="368582" parentID="368546" restricted="1" childCount="2"><dc:title>Various</dc:title><upnp:class>object.container</upnp:class></container></DIDL-Lite>
01-13 18:55:54.612 30838 30871 I SAXParser: Feature disallow-doctype-decl not known
01-13 18:55:54.613 30838 30871 I SAXParser: can't set factory.setXIncludeAware(false);

```

**Comment by tobexyz** [comment]
Hmm, thanks. The part of your log shows, that the first chunk is loaded an returned 10 directories. So far so good. The question is why the app nevertheless hangs? Is there any timeout shown in the log like it was in the released version?   
I mean this kind of message:

> I InputDispatcher: Application is not responding: Window{8570bc5 u0 de.yaacc/de.yaacc.browser.TabBrowserActivity}. It has been 5003.5ms since event, 5003.3ms since wait started. Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. Wait queue length: 5. Wait queue head age: 5706.5ms.

I would expect there isn't one.

**Comment by cweiske** [comment]
Oh, you are right. YAACC does not hang anymore and I can switch tabs even after browsing. So the hang is gone.

Unfortunately, the folder list is empty.

**Comment by tobexyz** [comment]
Ok, thanks! So we are getting closer, now we have to look why the browsing result doesn't appears. Do you found a message ```Ended AsyncTask for loading:``` in your log? 
I think I've to add some more log messages and add a visualization during loading.

**Comment by cweiske** [comment]
No. I waited several minutes, but there was no "ended" message.

**Comment by cweiske** [comment]
I started YAACC from AndroidStudio, and it worked in both debug and non-debug "run" mode. I always saw all the directories, and even long lists loaded.

However, when using the .apk created with "./gradlew build" (`yaacc/build/outputs/apk/debug/yaacc-debug.apk`), I have the list-is-empty problem described above.

**Comment by tobexyz** [comment]
that's an interesting behaviour and a useful hint, thx.! I've seen something similar a few releases ago. In that case the debug.apk works fine but the release.apk doesn't work. I needed to add some additional log statements to fix it. Maybe there is a kind of byte code optimization? I've to read about it...

**Comment by tobexyz** [comment]
I've just released version 2.2.0 and it will be available on f-droid in a few days. Please check if the bug is fixed then

**Comment by cweiske** [comment]
I version 2.2.0 from f-droid, I still see the problem tha the list is empty (except that it now shows "Loading..."). I guess the debug vs. non-debug problem is still active.

**Comment by cweiske** [comment]
With `async_load_issues`, I always get the content list when starting YAACC. What does not work at all anymore is clicking on a folder in that initial list; the list then stays at "Loading..." forever.

Also after the initial list display, switching to the "sender" tab and then clicking my server does not list the content at all.

**Comment by tobexyz** [comment]
@cweiske Thanks for testing yaacc in that detail!
I reduced the thread pool size for loading the content to only one thread (Class Yaacc line 47). Don't know if it is a fix. Please give it another try. It's a pity as long as I can not reproduce it we need to do tries like this

**Comment by cweiske** [comment]
Test for revision cf3571d:

When I started the new version the first time, it loaded the main content without problems, and I could browse all the folders - even the album folder with 300+ entries. All worked very nice.

Then I stopped yaacc with the "Exit"/Beenden menu item, killed the remainings via the app info, and started it again, and it hang a "Loading..." the initial content of my server.

When stopping it by showing the open apps list and swiping it away, and then starting it again, I have a one-in-three chance that the folder list works.

Re detailled testing: I desperately wish for a decent open source UPnP controller for android, and this here is my chance :)

**Comment by tobexyz** [comment]
Hi @cweiske, 
I'm a bit busy at the moment, so I'm not able to work a lot on this project. However I made a next try based on your writing. After resuming the app it tries to load the last position, maybe this causes problems sometimes. So now the app only loads the main folder. Let me know if it solves the problem.

P.S. If I will be near Leipzip I'll let you know :-)

**Comment by tobexyz** [comment]
today I added an option to do the content browse in a single threaded. It is configured as default setting and maybe this solves the problem on your device. As long as I can't reproduce this behavior on my hardware it is not easy to find a solution. 
However I integrated the branch ```async_load_issues``` into develop because I thought the things are now better than worse. I'm going to release the develop branch in the next days and then we will look and see how the response looks like...

**Comment by tobexyz** [comment]
hopefully fixed in version 2.3.0

**Comment by cweiske** [comment]
Sorry, but with 2.3.0 the state is the same as it was before :/

**Comment by phpbg** [comment]
Hi,
thanks for this nice app
+1 for this bug, even on 2.3.0
Android ask to kill app when launching music, but it occurs randomly...

**Comment by ccpp** [comment]
Hi, thank you for your good work. I can confirm this issue, or I have a similar issue:

* Experienced with all YAACC versions available on  F-Droid (2.3.0, 2.2.0, and 2.1.1).
* ZTE Blade phone
* UPnP server: Fritz!Box MediaServer (FritzNAS)

The app crashes when running YAACC for a few seconds (no need to interact with it).

```
09-11 21:02:33.513   937  1000 E ActivityManager: ANR in de.yaacc
09-11 21:02:33.513   937  1000 E ActivityManager: PID: 3081
09-11 21:02:33.513   937  1000 E ActivityManager: Reason: Context.startForegroundService() did not then call Service.startForeground()
09-11 21:02:33.513   937  1000 E ActivityManager: Load: 0.0 / 0.0 / 0.0
09-11 21:02:33.513   937  1000 E ActivityManager: CPU usage from 30315ms to 0ms ago (2022-09-11 21:02:03.061 to 2022-09-11 21:02:33.376):
```

Does this help? Is it the same issue as the one described above?

**Comment by tobexyz** [comment]
fixed during current refactoring on   https://github.com/tobexyz/yaacc-code/tree/feat/fixes_and_versions

**Comment by cweiske** [comment]
Branch `fixes_and_versions` with commit `a2e137c` does not hang anymore. Thank you for your work!

**Comment by ccpp** [comment]
Thank you very much for  your work!
Unfortunately, I cannot test this, adb install fails:
```
adb: failed to install yaacc-aligned-signed-2.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl989670478.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #28 (current version is #27)]
```
I even updated my android SDK. What do I need to do?

**Comment by cweiske** [comment]
YAACC now wants a phone with SDK 28, while your phone provides SDK 27.

**Comment by tobexyz** [comment]
@cweiske sdk28 is not really needed, now the min sdk level is 27

**Comment by ccpp** [comment]
🎉 works for me now. I can now also confirm this issue resolved. Thank you!

**Comment by ccpp** [comment]
One more note related to this issue: I see that two notifications are always active, even if the local server is disabled. Can this be improved to only show when the service is actually running?

**Comment by tobexyz** [comment]
The notification appears because the player service is always running but of course I could have a look how the notification can be removed. 
At the moment I am focusing of making yaacc running with the new network stack and more modern android SDK level. I want to release that soon.

After that I am able to improve the app. Please make a new issue for this.
