### ISSUE TITLE
Doesn't work with kodi

### ISSUE THREAD

**Issue by stemy2** [tobexyz/yaacc-code#19]
Hello,

Upnp and dlna services are activated on kodi and are on the same network, but kodi doen't appear anywhere in the app.

**Comment by tobexyz** [comment]
can't reproduce. I'm using kodi too and the receiver appears in the app.

**Comment by tobexyz** [comment]
Rechecked, can't reproduce. Kodi is working with yaacc. I am using it in my Setup, too.
