### ISSUE TITLE
Update UI-Design

### ISSUE THREAD

**Issue by tobexyz** [tobexyz/yaacc-code#20]
The UI is a bit outdated and should be redesigned. 
Flow idea: 
list all receivers -> select a receiver -> choose media source -> play
link receivers together and create a virtual device for it. List them like other receivers in the network

**Comment by aabaker** [comment]
It would be nice in such a redesign to be able to see and edit the playlist.

**Comment by tobexyz** [comment]
will be included in upcoming release 4.0.0
