### ISSUE TITLE
App ignores settings for third-party apps

### ISSUE THREAD

**Issue by franconian** [tobexyz/yaacc-code#21]
YAACC v 2.1, Android 7.1.2 

Current behaviour: Despite disabling the YAACC image viewer in settings it starts when streaming photos from a NAS to mobile. 

Expected behaviour: Request which third-party app should be used.

**Comment by tobexyz** [comment]
fixed with commit 9c4a32c9c675ee97715ab39ebfd7ed772bfd4e9c

**Comment by tobexyz** [comment]
fixed with version 2.3.0
