### ISSUE TITLE
Settings for media types ignored

### ISSUE THREAD

**Issue by franconian** [tobexyz/yaacc-code#23]
YAACC 2.1, Android 7.1.2 

Settings: Ignore music and video files, show images 

Current behaviour: All media types on all devices are visible.

**Comment by tobexyz** [comment]
You are right. thx. 
After looking into the code I realized that they are useless.  I am going to remove them

**Comment by tobexyz** [comment]
I've just released version 2.2.0 and it will be available on f-droid in a few days. In it the useless settings are removed
