### ISSUE TITLE
"Exit" button does not stop YAACC

### ISSUE THREAD

**Issue by cweiske** [tobexyz/yaacc-code#28]
The exit button introduced with commit 6d49c6ce0aacbc9e403d4161e238de712e9718d2 does not stop YAACC completely.

On "adb logcat", I still see "de.yaacc.upnp.UpnpClient: remoteDeviceUpdated" messages.
On the shell, "ps | grep yaacc" gives one line output.

I have to stop it via the app settings to really stop it.

This is on a Nexus 7 tablet with LineageOS 14.1 (Android 7.1.2).

I'm running the async_load_issues branch, but this also happens with 2c06b13.

**Comment by tobexyz** [comment]
fixed with version 2.3.0
