### ISSUE TITLE
Content tab says 'loading...' forever

### ISSUE THREAD

**Issue by iteco** [tobexyz/yaacc-code#30]
I just installed the app from f-droid (version 2.2.0) and went to 'content' tab. I am expecting it to show my local files on the device, but it just shows 'Loading...' text forever. There is icon (arrow pointing down to a line) in front of that text. If I click that icon, the app will crash and the OS will say that 'YAACC' has stopped.

**Comment by tobexyz** [comment]
You need to select a upnp server first. After that the content tab shows the contents of the server.
Local files are only shown, if you activate the local UpnpServer in the settings.
The content tab should not shown anything if no server is selected. I.e. showing 'Loading...' in this case might be a bug

**Comment by tobexyz** [comment]
duplicate to #16
