### ISSUE TITLE
YAACC using mobile data

### ISSUE THREAD

**Issue by BCMM** [tobexyz/yaacc-code#37]
Yesterday, YAACC somehow used 259MB of mobile data in just a couple of hours away from the home WiFi. I am not sure what state I left the app in, but I had been using it shortly prior to going out.

Needless to say, none of my other UPNP devices were accessible to the phone over cellular internet, so I have no idea what it actually did with all that data.

**Comment by tobexyz** [comment]
I don't know what was going on. Maybe  you previously played content from the internet like live streams or other content? Your upnp server delivers only the url of the content. The content url then is played by yaacc. If the content url is target to the internet it would be also playable outside your LAN

**Comment by tobexyz** [comment]
cleanup stale issue
