### ISSUE TITLE
Develop branch: Could not determine dependencies

### ISSUE THREAD

**Issue by christf** [tobexyz/yaacc-code#43]
01:17 $ ./gradlew build
Earlier today I attempted to compile yaac and failed;

>Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status 
> for details
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':yaacc:lintVitalRelease'.
> > Could not resolve all artifacts for configuration ':yaacc:debugCompileClasspath'.
>    > Could not find org.fourthline.cling:cling-core:2.1.2.yaacc_2.
>      Required by:
>          project :yaacc
>    > Could not find org.fourthline.cling:cling-support:2.1.2.yaacc_2.
>      Required by:
>          project :yaacc
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org

I added the fourthline mvn repository, removed the yacc specific version from the build config and was able to build with the upstream version. When starting the app, no servers are shown. I suspect cause to be me including a different dependency (upstream vs the yaacc included). 

What is the proper way to build this software?

**Comment by tobexyz** [comment]
did you install maven on your machine, too? During the build the cling-repos are fetched and compiled. These repos using maven as build tool. If maven is installed the build should be possible using `./gradlew build`

**Comment by christf** [comment]
maven is installed and ./greadlew build fails with the above message about cling-core and cling-support missing:
> $ mvn --version
> Apache Maven 3.6.0
> Maven home: /usr/share/maven
> Java version: 11.0.6, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64
> Default locale: de_DE, platform encoding: UTF-8
> OS name: "linux", version: "4.19.0-8-amd64", arch: "amd64", family: "unix"

**Comment by christf** [comment]
After having fetched cling-core and cling-common from maven, I was able to revert all my changes to the build.gradle file and ./gradlew build successfully.

I then tested to remove said jars from the m2 repo cache and sure enough, builds failed again. There is something going on here and it seems like gradle is not including the cling-core and cling-support packages as intended.

**Comment by tobexyz** [comment]
you are right. It seems the travis build is broken too after integrating the last PR. It must be a problem with the last commits.

**Comment by tobexyz** [comment]
hi, I fixed the build.  Please try it again.  `./gradlew build` should work now

**Comment by tobexyz** [comment]
clean stale issues...
