### ISSUE TITLE
Execution failed for task ':yaacc:javaPreCompileDebug'

### ISSUE THREAD

**Issue by nima-abdpoor** [tobexyz/yaacc-code#47]
I clone project without any changing but build failed with following description :

Execution failed for task ':yaacc:javaPreCompileDebug'.
> Could not resolve all files for configuration ':yaacc:debugCompileClasspath'.
   > Failed to transform file 'cling-core-2.1.2.yaacc_2.jar' to match attributes {artifactType=android-classes, org.gradle.usage=java-runtime-jars}
      > Execution failed for IdentityTransform: D:\projects\android\yaacc-code\clingbuild\build\poms\tobexyz-cling\core\target\cling-core-2.1.2.yaacc_2.jar.
         > D:\projects\android\yaacc-code\clingbuild\build\poms\tobexyz-cling\core\target\cling-core-2.1.2.yaacc_2.jar
   > Failed to transform file 'cling-support-2.1.2.yaacc_2.jar' to match attributes {artifactType=android-classes, org.gradle.usage=java-runtime-jars}
      > Execution failed for IdentityTransform: D:\projects\android\yaacc-code\clingbuild\build\poms\tobexyz-cling\support\target\cling-support-2.1.2.yaacc_2.jar.
         > D:\projects\android\yaacc-code\clingbuild\build\poms\tobexyz-cling\support\target\cling-support-2.1.2.yaacc_2.jar
   > Failed to transform file 'seamless-util-1.1.2.yaacc_1.jar' to match attributes {artifactType=android-classes, org.gradle.usage=java-runtime-jars}
      > Execution failed for IdentityTransform: D:\projects\android\yaacc-code\clingbuild\build\poms\seamless\util\target\seamless-util-1.1.2.yaacc_1.jar.
         > D:\projects\android\yaacc-code\clingbuild\build\poms\seamless\util\target\seamless-util-1.1.2.yaacc_1.jar
   > Failed to transform file 'seamless-xml-1.1.2.yaacc_1.jar' to match attributes {artifactType=android-classes, org.gradle.usage=java-runtime-jars}
      > Execution failed for IdentityTransform: D:\projects\android\yaacc-code\clingbuild\build\poms\seamless\xml\target\seamless-xml-1.1.2.yaacc_1.jar.
         > D:\projects\android\yaacc-code\clingbuild\build\poms\seamless\xml\target\seamless-xml-1.1.2.yaacc_1.jar

seems like couldn't  detect .jar files in clingbuild.

**Comment by tobexyz** [comment]
Hi @nima-abdpoor,
I just restartet the ci-build to see if anything went wrong over the time, but the build finished without any problems:  
https://travis-ci.org/github/tobexyz/yaacc-code/builds/661253536

The ci-build uses this script:
https://github.com/tobexyz/yaacc-code/blob/develop/.travis.yml
Maybe there are some useful information for you in the script. 

You need both maven and gradle to build this project. Maven is used to build the cling-project. Gradle for building yaacc. The gradle build of yaacc triggers the maven build for cling. Hope this information is helpful :-)
