### ISSUE TITLE
List views are re-painted when switching tabs even tough content stays the same

### ISSUE THREAD

**Issue by cweiske** [tobexyz/yaacc-code#48]
When switching between the tabs "Sender", "Content", "Receiver" and "Player", the tab content is visibly re-painted: The list is cleared, then the content is re-added to the list. This causes a flickering, even though the content of the list stays the same.

It would be nice if the list content would not be repainted if the content stays the same.

(This happens with a2e137c842e06547b88128fcd57c648545d846dd, branch `fixes_and_versions`.)

**Comment by tobexyz** [comment]
Thanks! I'll fix it in a next step. At the moment I am focusing on the principle functionality. After that I'll go into this

**Comment by tobexyz** [comment]
will be fixed  in upcoming release 4.0.0
