### ISSUE TITLE
Switching tabs scrolls through all tab contents

### ISSUE THREAD

**Issue by cweiske** [tobexyz/yaacc-code#49]
When switching from the first tab (Sender) to the last one (Players), the content of all tabs in between is scrolled through the view. This makes switching tabs longer than it should.

It would be nice if YAACC would only slide away the contents of the first tab and then immediately slide in the content of the selected last tab.

(This happens with a2e137c842e06547b88128fcd57c648545d846dd, branch fixes_and_versions)

**Comment by tobexyz** [comment]
Thanks for your help. I'll have a look on it

**Comment by tobexyz** [comment]
the behavior is maybe a result of using other components in the activity. Because of this and I am planning to implement a new ui flow in issue #20 I won't fix it.
