### ISSUE TITLE
Test fails: subscriptionLifecycleNotifyBeforeResponse FAILED

### ISSUE THREAD

**Issue by cweiske** [tobexyz/yaacc-code#55]
When running "gradlew build" on commit 326d8b0 I get an error:
```
> Task :yaacc:testReleaseUnitTest

org.fourthline.cling.test.gena.OutgoingSubscriptionLifecycleTest > subscriptionLifecycleNotifyBeforeResponse FAILED
    java.lang.AssertionError at OutgoingSubscriptionLifecycleTest.java:308

380 tests completed, 1 failed
```

This was after updating git from the fixes_and_versions branch to master.
When running "gradlew build" again this error does not appear again.

**Comment by tobexyz** [comment]
seems to be a problem in the timing of the threads within the test. I don't have a full understanding of the problem yet but I was able to reproduce the problem.  Sadly only once so it is hard to debug...

**Comment by tobexyz** [comment]
I never saw this problem again while building the app. I'll close this issue now.  We can reopen it, if the problem occurs more often
