### ISSUE TITLE
Share with http proxy

### ISSUE THREAD

**Issue by tobexyz** [tobexyz/yaacc-code#68]
Some old devices can't handle https URLs. For such devices the share feature does not work because all shared URLs from the internet should be https URLs. 
Allow to use the yaacc server service as a proxy in this case which publishes the Https URL as http URL in the local network.

**Comment by ildar** [comment]
I am not sure, but this may be critical for me too:
I can't get my TV to show anything from the web, e.g.
https://sample-videos.com/ . The reason might be this HTTPS problem.

**Comment by tobexyz** [comment]
On old devices I have got the problem that the device silently not playing the content, if it is a HTTPS URL.

You can try the current bugfixing branch to see if the proxy helps in your case.

I am doing some last tests before I am going to release the proxy feature. For me it looks quite stable now.

**Comment by ildar** [comment]
unfortunately Github actions don't build and export apks. It'll take some
time to build the branch.
I'll let you know..

**Comment by tobexyz** [comment]
part of release 4.2.0
