### ISSUE TITLE
Oreo adaptive icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [tobexyz/yaacc-code#7]
Please add support for icon shape

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by tobexyz** [comment]
it's hopefully implemented in release 2.1.0

**Comment by c-e-p-x-u-o** [comment]
![img_20190102_052916](https://user-images.githubusercontent.com/14617699/50592022-5a5ccc80-0ea3-11e9-84cc-c1024066c6f0.jpg)

**Comment by tobexyz** [comment]
ok, I see... I'll take a look at it. thx.

**Comment by tobexyz** [comment]
should be fixed in version 2.1.1

**Comment by c-e-p-x-u-o** [comment]
Yes, it's fixed in 2.1.1. Thank you!
