### ISSUE TITLE
display of albums is not full

### ISSUE THREAD

**Issue by nolon** [tobexyz/yaacc-code#9]
I have a large music collection and when using yaacc to browse for example artists it will only display about 100 artists not sure if this is an issue with yaacc or the cling lib can you please check
Thx

**Comment by tobexyz** [comment]
At the moment yaacc reads all items in a folder without any restrictions. Maybe that's the problem... If a collection is very large, the query won't come back in an acceptable time  or it possible that the server limits the result.  
I think the search has to be done in chunks, I'll have to take a look on it

**Comment by tobexyz** [comment]
I've implemented a first solution in branch ```issue#9```. Items now loaded async. It would be helpful if anyone can additionally confirm that the implementation on the branch fixes the problem.

**Comment by nolon** [comment]
I will try to test it this weekend if I have the time.
Let you know as soon as I can.

**Comment by tobexyz** [comment]
I've just released version 2.2.0 and it will be available on f-droid in a few days. Please check if the bug is fixed then

**Comment by nolon** [comment]
OK will do
Thx

**Comment by nolon** [comment]
No luck the list goes up to the letter F. But not more

**Comment by nolon** [comment]
False alarm my version was still old I can browse all the albums now

Thx again
