### ISSUE TITLE
Not much space for media browsing in landscape mode 

### ISSUE THREAD

**Issue by cweiske** [tobexyz/yaacc-code#92]
I want to repurpose my old Wileyfox Swift as bedroom nightstand clock + music player and want to mount it in landscape mode.

Unfortunately browsing files with YAACC in landscape mode is not very user friendly:
- only 2 content lines from the server are visible
- bottom shows the server I am browsing, which I don't need
- bottom shows the local server on the device that i disabled, so I don't want to see that as well.
- the headline "YAACC" could also be hidden to make more space
- the main navigation icons + labels (sender, content, receiver) could be on one line

![20240115-203758_YAACC](https://github.com/tobexyz/yaacc-code/assets/59036/dd704623-3578-4db5-9b27-8de82ecea202)

**Comment by cweiske** [comment]
Inside a folder there is only one row of folder content visible because of the breadcrumb:
![2024-01-18 browse](https://github.com/tobexyz/yaacc-code/assets/59036/8a7206f8-f750-4e01-b08f-33df0420f6b7)

**Comment by tobexyz** [comment]
![Screenshot_20240120-155434.png](https://github.com/tobexyz/yaacc-code/assets/40026159/404cace1-9600-4f20-9df6-47852a28ce5b)

That's how it looks like now. 
I think we can go with this solution...

**Comment by cweiske** [comment]
Could you put the main navigation icons + labels (sender, content, receiver) on one line, or does that make the touch area too small? (But swiping would still be possible)

**Comment by tobexyz** [comment]
Yes, it's possible, take a look...

![Screenshot_20240120-225843.png](https://github.com/tobexyz/yaacc-code/assets/40026159/474e3429-9978-486d-9415-fe74284208b5)

**Comment by tobexyz** [comment]
the issue will be part of the next upcoming release
