### ISSUE TITLE
Landscape mode: Put cover image left of song info

### ISSUE THREAD

**Issue by cweiske** [tobexyz/yaacc-code#94]
When in landscape mode, the cover image is very small. It would be nice if the cover got the left half of the screen, while the song info and play buttons would be on the right.

Current status:
![2024-01-18 yaacc player](https://github.com/tobexyz/yaacc-code/assets/59036/10b32d54-4209-47e9-8d3f-13aa85f03479)

**Comment by tobexyz** [comment]
![Screenshot_20240120-163159.png](https://github.com/tobexyz/yaacc-code/assets/40026159/383e0efc-4376-47fb-b1de-23816ac52aaf)

That's how it looks like now...

**Comment by cweiske** [comment]
That looks great!

**Comment by tobexyz** [comment]
this issue will be solved in the next upcoming release
